export default [{
        imageUrl: 'bR.png',
        start_position: 'a8',
        new_position: 'a8',
        captured: false,
    },
    {
        imageUrl: 'bR.png',
        start_position: 'h8',
        new_position: 'h8',
        captured: false,
    },
    {
        imageUrl: 'bN.png',
        start_position: 'b8',
        new_position: 'b8',
        captured: false,
    },
    {
        imageUrl: 'bN.png',
        start_position: 'g8',
        new_position: 'g8',
        captured: false,
    },
    {
        imageUrl: 'bB.png',
        start_position: 'c8',
        new_position: 'c8',
        captured: false,
    },
    {
        imageUrl: 'bB.png',
        start_position: 'f8',
        new_position: 'f8',
        captured: false,
    },
    {
        imageUrl: 'bQ.png',
        start_position: 'd8',
        new_position: 'd8',
        captured: false,
    },
    {
        imageUrl: 'bK.png',

        start_position: 'e8',
        new_position: 'e8',
        captured: false,
    },
    {
        imageUrl: 'bP.png',
        start_position: 'a7',
        new_position: 'a7',
        captured: false,
    },
    {
        imageUrl: 'bP.png',
        start_position: 'b7',
        new_position: 'b7',
        captured: false,
    },
    {
        imageUrl: 'bP.png',
        start_position: 'c7',
        new_position: 'c7',
        captured: false,
    },
    {
        imageUrl: 'bP.png',
        start_position: 'd7',
        new_position: 'd7',
        captured: false,
    },
    {
        imageUrl: 'bP.png',
        start_position: 'e7',
        new_position: 'e7',
        captured: false,
    },
    {
        imageUrl: 'bP.png',
        start_position: 'f7',
        new_position: 'f7',
        captured: false,
    },
    {
        imageUrl: 'bP.png',
        start_position: 'g7',
        new_position: 'g7',
        captured: false,
    },
    {
        imageUrl: 'bP.png',
        start_position: 'h7',
        new_position: 'h7',
        captured: false,
    },
    {
        imageUrl: 'wR.png',
        start_position: 'a1',
        new_position: 'a1',
        captured: false,
    },
    {
        imageUrl: 'wR.png',
        start_position: 'h1',
        new_position: 'h1',
        captured: false,
    },
    {
        imageUrl: 'wN.png',
        start_position: 'b1',
        new_position: 'b1',
        captured: false,
    },
    {
        imageUrl: 'wN.png',
        start_position: 'g1',
        new_position: 'g1',
        captured: false,
    },
    {
        imageUrl: 'wB.png',
        start_position: 'c1',
        new_position: 'c1',
        captured: false,
    },
    {
        imageUrl: 'wB.png',
        start_position: 'f1',
        new_position: 'f1',
        captured: false,
    },
    {
        imageUrl: 'wQ.png',
        start_position: 'd1',
        new_position: 'd1',
        captured: false,
    },
    {
        imageUrl: 'wK.png',

        start_position: 'e1',
        new_position: 'e1',
        captured: false,
    },
    {
        imageUrl: 'wP.png',
        start_position: 'a2',
        new_position: 'a2',
        captured: false,
    },
    {
        imageUrl: 'wP.png',
        start_position: 'b2',
        new_position: 'b2',
        captured: false,
    },
    {
        imageUrl: 'wP.png',
        start_position: 'c2',
        new_position: 'c2',
        captured: false,
    },
    {
        imageUrl: 'wP.png',
        start_position: 'd2',
        new_position: 'd2',
        captured: false,
    },
    {
        imageUrl: 'wP.png',
        start_position: 'e2',
        new_position: 'e2',
        captured: false,
    },
    {
        imageUrl: 'wP.png',
        start_position: 'f2',
        new_position: 'f2',
        captured: false,
    },
    {
        imageUrl: 'wP.png',
        start_position: 'g2',
        new_position: 'g2',
        captured: false,
    },
    {
        imageUrl: 'wP.png',
        start_position: 'h2',
        new_position: 'h2',
        captured: false,
    },
];